name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy to AWS
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            echo "Starting deployment....."

            cd /var/www/todoapp

            echo "Checking production environment..."
            test -f .env

            echo "Fetching latest code..."
            git fetch origin main

            echo "Updating application..."
            git reset --hard origin/main

            echo "Fixing Laravel permissions..."
            sudo chown -R ubuntu:www-data storage bootstrap/cache
            sudo chmod -R ug+rwX storage bootstrap/cache

            echo "Installing production dependencies..."
            composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction

            echo "Running database migrations..."
            php artisan migrate --force

            echo "Clearing Laravel caches..."
            php artisan optimize:clear

            echo "Rebuilding Laravel caches..."
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            echo "Deployment completed successfully!!!!"

      - name: Verify deployment
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            cd /var/www/todoapp

            echo "Verifying deployment......"

            echo "Current commit:"
            git rev-parse HEAD

            echo "Laravel version:"
            php artisan --version

            echo "Git status:"
            git status --short

            echo "Deployment verification successful!"
